### PR TITLE
[ADD] Split website_sale_search_custom into 2 modules

### PR DESCRIPTION
**Pull request by jbchouinard**
the custom search module contains 2 functionalities: clearing the search on category change, and
searching product tags. each functionality was split into a separate module (website_sale_search_tags
and website_sale_search_clear)

we only needed to clear the search bar for one of our clients, so we split the module.

feel free to merge this if you want.

### CODE REVIEW

**Comment by yelizariev** [comment]
@jbchouinard Thanks! You fix old issue I thought about. 
Before merging this, I want to modify ``website_sale_search_custom`` and add there two modules to dependencies for backward compatibility.
Also, I need to update description of the new modules.

**Comment by jbchouinard** [comment]
@yelizariev ok, I didnt touch the original module to avoid breaking anything, making it an empty module that depends on the other two seems like a reasonable solution.

**Comment by yelizariev** [comment]
@jbchouinard we are about to finish mentioned updates, so you don't need to worry about it. Thank you for the work you have already done.

**Comment by yelizariev** [comment]
We have merged the updates here: https://github.com/it-projects-llc/website-addons/pull/140

**Pull request closed without merging**
