### PR TITLE
:tada::one::one: multi_attachment_product_image module

### PR DESCRIPTION
**Pull request by ilmir-k**
:tada::one::one: multi_attachment_product_image module

### CODE REVIEW

**Comment by yelizariev** [comment]
too red

**Comment by ilmir-k** [comment]
@yelizariev 
As I see the travis error is not related to the ``multi_attachment_product_image`` module. How we should proceed?

cc @KolushovAlexandr

**Comment by KolushovAlexandr** [comment]
@ilmir-k restarted PRs tests, "KeyError: 'body'" was resolved in mail_multi_company module, hope tests are gonna pass

**Comment by ilmir-k** [comment]
@KolushovAlexandr it's ok now so let's approve it

**Comment by KolushovAlexandr** [comment]
@ilmir-k Your turn

**Pull request merged**
