### PR TITLE
[REF] compatibility checkout_store with website_sale_delivery

### PR DESCRIPTION
**Pull request by KolushovAlexandr**

### CODE REVIEW

**Comment by yelizariev** [comment]
@KolushovAlexandr fix conflicts please

**Comment by yelizariev** [comment]
@ilmir-k please review

**Comment by yelizariev** [comment]
Some problem in tour shop_mandatory_fields_nobill_noship


```
2018-08-28 11:33:57,649 5284 INFO openerp_test werkzeug: 127.0.0.1 - - [28/Aug/2018 11:33:57] "POST /shop/get_order_numbers HTTP/1.1" 200 -
2018-08-28 11:34:07,642 5284 INFO openerp_test odoo.tests.common: phantomjs: Tour shop_mandatory_fields_nobill_noship: step .div_name input[name="name"] succeeded
2018-08-28 11:34:17,668 5284 INFO openerp_test odoo.tests.common: phantomjs: Tour shop_mandatory_fields_nobill_noship: step #div_email input[name="email"] succeeded
2018-08-28 11:34:27,691 5284 INFO openerp_test odoo.tests.common: phantomjs: Tour shop_mandatory_fields_nobill_noship: step #div_phone input[name="phone"] succeeded
2018-08-28 11:34:37,721 5284 INFO openerp_test odoo.tests.common: phantomjs: Tour shop_mandatory_fields_nobill_noship: step a:contains("Next") succeeded
2018-08-28 11:34:38,482 5284 INFO openerp_test werkzeug: 127.0.0.1 - - [28/Aug/2018 11:34:38] "POST /shop/address HTTP/1.1" 302 -
2018-08-28 11:34:38,632 5284 INFO openerp_test werkzeug: 127.0.0.1 - - [28/Aug/2018 11:34:38] "GET /shop/checkout HTTP/1.1" 302 -
2018-08-28 11:34:38,936 5284 INFO openerp_test odoo.models.unlink: User #1 deleted sale.order.line records with IDs: [44]
2018-08-28 11:34:39,366 5284 INFO openerp_test odoo.models.unlink: User #1 deleted sale.order.line records with IDs: [45]
2018-08-28 11:34:39,841 5284 INFO openerp_test werkzeug: 127.0.0.1 - - [28/Aug/2018 11:34:39] "GET /shop/payment HTTP/1.1" 200 -
2018-08-28 11:34:39,968 5284 INFO openerp_test werkzeug: 127.0.0.1 - - [28/Aug/2018 11:34:39] "POST /website/translations HTTP/1.1" 200 -
2018-08-28 11:35:00,263 5284 INFO openerp_test odoo.tests.common: phantomjs: _check_for_tooltip
2018-08-28 11:35:00,264 5284 INFO openerp_test odoo.tests.common: phantomjs: - modal_displayed: 0
2018-08-28 11:35:00,266 5284 INFO openerp_test odoo.tests.common: phantomjs: - trigger 'h2:contains(Thank you for your order)': 0
2018-08-28 11:35:00,267 5284 INFO openerp_test odoo.tests.common: phantomjs: - visible trigger 'h2:contains(Thank you for your order)': 0
2018-08-28 11:35:00,269 5284 INFO openerp_test odoo.tests.common: phantomjs: - extra_trigger 'h2:contains(Thank you for your order)': 0
2018-08-28 11:35:00,270 5284 INFO openerp_test odoo.tests.common: phantomjs: - visible extra_trigger 'h2:contains(Thank you for your order)': 0
2018-08-28 11:35:00,513 5284 INFO openerp_test odoo.tests.common: phantomjs: <body>

```

**Comment by ilmir-k** [comment]
> After confirmation, the orders do not appear in the Sales->Sales/Sales Orders, but they can be found in Sales->Sales/Quotations

@Ramil-Mukhametzyanov It seems that you try to fix built-in behavior. Check how it works without our module first and let me know if it works the same.

**Comment by ilmir-k** [comment]
@Ramil-Mukhametzyanov so what the next? do you have another issue or it can be approved?

**Comment by ilmir-k** [comment]
@yelizariev I think we can merge it

**Comment by ilmir-k** [comment]
I approve to merge it now

**Pull request merged**
