### PR TITLE
[ADD] website-addons: Add .gitignore

### PR DESCRIPTION
**Pull request by t3ddftw**
* Add .gitignore for common python files that shouldn't be track by VCS

### CODE REVIEW

**Comment by yelizariev** [comment]
@t3ddftw you are probably fifth person, who are trying to add ``.gitignore`` file. 
Thank you for your efforts, but I don't accept such updates. I recommend to use global gitignore file in your system. I believe, that gitignore in repo is required to ignore very specific rules. For example, when some script\Makefile produce specific files in directory, that shall not be pushed to the repo. I don't see the reason to add gitignore in this repo. Another explanation is that there is no gitignore file that fit to all developers and they need own global gitignore files anyway

**Comment by lasley** [comment]
Gitignore is useful for everyone using the repo, which is why you have had so many submissions on the subject. There are a set of files that no Odoo dev wants committed to the repo; not adding a gitignore just makes it harder for someone to work in your code. 

Not a problem though, we will make note of your decision & just add to our forks. I recommend you read further on this subject, however:

* https://help.github.com/articles/ignoring-files/#create-a-local-gitignore
* https://stackoverflow.com/questions/5765645/should-you-commit-gitignore-into-the-git-repos
* https://stackoverflow.com/questions/767147/ignore-the-gitignore-file-itself

**Comment by yelizariev** [comment]
@lasley thank you for sharing your thoughts. 
I still don't have an answer why people cannot use global gitignore for common extensions. But probably your are right and I shall not force them to do it, even if it's a right thing. If someone prefers to use gitignore per project, why don't add it. I prefer to don't add gitignore file per project, because I had a feeling that it's not clean thing. I see, that many gitignores have extentensions I don't understand or I am sure cannot be found in a project (e.g. c files in python project ``*.so``). But I can accept it it just personally ignore ``gitignore`` in repos

**Comment by yelizariev** [comment]
Is some of you able to restore branch to merge it?

**Comment by lasley** [comment]
@yelizariev - Global gitignore is really meant for things at the OS level. Our specific issue with this is that we are not specifically Odoo (or even Python) developers. Some things that work for one repo don't work for another, and that is where the locals come in.

The `gitignore` that @t3ddftw proposed is directly from [OCA repo](https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.gitignore), which we maintain specifically for Odoo. Honestly this has been a godsend in terms of our development workflows, particularly with our diverse internal environments.

Branch restored 😄

**Comment by yelizariev** [comment]
So, you guys are the last who was trying to add gitignore and the first whose proposal is accepted :smile:

**Pull request merged**
