### PR TITLE
[MIG] website_sale_stock_status: Upgrade to 9.0

### PR DESCRIPTION
**Pull request by t3ddftw**
Hello!

I've gone ahead and upgraded this module for use with 9.0. I also made some changes to the directory structure. My apologies for the unclean diff - let me know if there's anything I can clarify or do to help.

Thanks!

### CODE REVIEW

**Comment by yelizariev** [comment]
@t3ddftw Sorry for late response. 

It's difficult to review the updates. There are two way to fix it:

* (reset \ new branch is required) make a two separate commits: one for files relocation and another for update
* (more simple) return files to original location. I can do it myself, but the update will be delayed. 

Thank you anyway for sending your work.

**Comment by t3ddftw** [comment]
Hey @yelizariev,

I went ahead and split the change into two commits, as suggested in option 1. This should allow you review the changes much more easily.

Thanks!
-Ted

**Comment by yelizariev** [comment]
@t3ddftw 
actually, there are three types of updates:
* migration
* style update (indentation and other)
* file layout update

As I understand, migration parts includes only removing this item:

    <template id="products" inherit_id="website_sale.products" name="Products">

While I agree with your "style" updates and file layout updates, I have concern about applying it on existed modules. Usually, we don't make style updates. Then only exception is fixing lint warnings. The reason why we don't do it is because it blows git history -- git blame would show style commits instead of essential ones.
In your case there is another concern: if we apply these style updates to 9.0 only, then I there will be problems with merging updates of the module from 8.0 branch.

So, I recommend to apply only essential updates (actual migration and contribution info) and keep old style of the code.

**Comment by t3ddftw** [comment]
@yelizariev,

I have updated the PR with only the base essentials to getting this module upgraded, as requested.

Thanks!

**Comment by yelizariev** [comment]
Thanks.

There is still non-essential updates in xml files. You have updated indent there and it makes diff bigger and hard to read. Please, update it too. I have the same concerns about it.

**Comment by t3ddftw** [comment]
@yelizariev,

Take a look now. There's a comment in the XML that I moved, let me know if that's going to be of concern.

Thanks!

**Comment by yelizariev** [comment]
@t3ddftw thanks for patience :+1:

**Pull request merged**
