### PR TITLE
:one::two::arrow_up: website_sale_checkout_store

### PR DESCRIPTION
**Pull request by trojikman**

### CODE REVIEW

**Comment by yelizariev** [comment]
@trojikman fix lints

**Comment by yelizariev** [comment]
The modules is not installed:
```

018-07-03 13:29:59,298 5063 INFO openerp_test odoo.modules.loading: loading website_sale_checkout_store/templates.xml
2018-07-03 13:29:59,557 5063 INFO openerp_test odoo.addons.base.ir.ir_ui_view: Element '<xpath expr="//div[hasclass('row')]//a[hasclass('btn','btn-primary','pull-right')][@href='/shop/checkout?express=1']">' cannot be located in parent view
Error context:
View `my_cart`
[view_id: 822, xml_id: n/a, model: n/a, parent_id: 787]
2018-07-03 13:29:59,560 5063 WARNING openerp_test odoo.modules.loading: Transient module states were reset
2018-07-03 13:29:59,560 5063 ERROR openerp_test odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
File "/home/travis/odoo-11.0/odoo/models.py", line 1036, in _validate_fields
check(self)
File "/home/travis/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 330, in _check_xml
view_def = view.read_combined(['arch'])
File "/home/travis/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 714, in read_combined
arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
File "/home/travis/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 663, in apply_view_inheritance
source = self.apply_inheritance_specs(source, specs_tree, view_id)
File "/home/travis/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 641, in apply_inheritance_specs
self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
File "/home/travis/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 503, in raise_view_error
raise ValueError(message)
ValueError: Element '<xpath expr="//div[hasclass('row')]//a[hasclass('btn','btn-primary','pull-right')][@href='/shop/checkout?express=1']">' cannot be located in parent view
```

**Comment by yelizariev** [comment]
@trojikman please use space between tag and message

:fire_engine: change triggers to correct
:fire_engine:change triggers to correct

**Comment by ilmir-k** [comment]
I have the error on runbot:

```
Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/tools/convert.py", line 745, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/tools/convert.py", line 723, in _tag_template
    return self._tag_record(record, data_node)
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/tools/convert.py", line 655, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/models.py", line 3710, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/addons/base/models/ir_ui_view.py", line 401, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/models.py", line 3452, in create
    fields[0].determine_inverse(batch_recs)
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/fields.py", line 1100, in determine_inverse
    getattr(records, self.inverse)()
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/addons/base/models/ir_ui_view.py", line 265, in _inverse_arch
    view.write(data)
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/addons/base/models/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/models.py", line 3169, in write
    self._write(store_vals)
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/models.py", line 3315, in _write
    self._validate_fields(vals)
  File "/mnt/odoo-extra/runbot/static/build/19162-338-e46036/odoo/models.py", line 1097, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<xpath expr="//div[hasclass(\'row\')]//a[hasclass(\'btn\',\'btn-primary\',\'pull-right\')][@href=\'/shop/checkout?express=1\']">\' cannot be located in parent view\n\nError context:\nView `my_cart`\n[view_id: 878, xml_id: n/a, model: n/a, parent_id: 855]', None)

```
It was already mentioned above

**Pull request merged**
